



const ORGANISATION_ID = 3
const TEMP_REG_LABEL = 'TEMP_REG_LABEL'
const INPUT_TYPES = {
	TEXT: 'TEXT',
	PASSWORD: 'PASSWORD',
	NUMBER: 'NUMBER',
	EMAIL: 'EMAIL',
	DATE: 'DATE',
	PHONE: 'PHONE',
	DATE_PICKER: 'DATE_PICKER',
	SELECT: 'SELECT',
	RADIO: 'RADIO',
	CURRENCY: 'CURRENCY',
	DEFAULT: 'TEXT'
}

export default {
	TEMP_REG_LABEL,
	INPUT_TYPES,
	ORGANISATION_ID
}